[package]
name = "dotman"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
colored = "3.0.0"
dirs = "6.0.0"
hex = "0.4.3"
serde = { version = "1.0.219", features = ["derive"] }
sha2 = "0.10.9"
toml = "0.8.23"
walkdir = "2.5.0"
